apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
#we can have single build context in skaffold.yaml file
build:
  local:
    push: false
  artifacts:
    # - image: us.gcr.io/ticketing-dev-440902/auth
    - image: smaug30/nodejs-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            # dest: . means throw the files in src to running directory of container
            dest: .
    - image: smaug30/nodejs-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            # dest: . means throw the files in src to running directory of container
            dest: .
    - image: smaug30/nodejs-tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            # dest: . means throw the files in src to running directory of container
            dest: .
    - image: smaug30/nodejs-orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: smaug30/nodejs-expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: smaug30/nodejs-payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
