name: tests-auth

on:
  pull_request:
    paths:
      - 'auth/**' #this means that if any file inside auth directory changes then run this script

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && npm install && npm run test:ci
    
